[workspace]
members = ["hal", "loader"]
exclude = ["acpi"]

[package]
name = "kernel"
version = "0.1.0"
authors = ["Isaac Woods"]
edition = "2024"

[dependencies]
hal = { path = "hal" }
tracing-core = { git = "https://github.com/tokio-rs/tracing", branch = "v0.2.x", default-features = false }
tracing = { git = "https://github.com/tokio-rs/tracing", branch = "v0.2.x", default-features = false }
acpi = { path = "acpi" }
bitfield = { path = "../lib/bitfield" }
