[package]
name = "seed"
version = "0.1.0"
authors = ["Isaac Woods"]
edition = "2021"

[dependencies]
hal = { path = "../lib/hal" }
heapless = "0.8.0"
serde = { version = "1", default-features = false, features = ["derive", "alloc"] }
