#!/bin/sh

# Exit on error
set -e

RUSTC_SYSROOT="$(rustc --print=sysroot)"
GDB_PYTHON_MODULE_DIR="$RUSTC_SYSROOT/lib/rustlib/etc"
PYTHONPATH="$PYTHONPATH:$GDB_PYTHON_MODULE_DIR" exec gdb \
    --directory="$GDB_PYTHON_MODULE_DIR" \
    -iex "add-auto-load-safe-path $GDB_PYTHON_MODULE_DIR" \
    "$@"
