name: Deploy site

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        default: true
        profile: minimal
        components: rust-src

    - name: Install Rust (RV64)
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target: riscv64imac-unknown-none-elf
        default: true
        profile: minimal
        components: rust-src

    - name: Install Rust (x86 UEFI)
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target: x86_64-unknown-uefi
        default: true
        profile: minimal
        components: rust-src

    - name: Install dependencies
      run: |
        cargo install mdbook
        sudo apt-get update
        sudo apt-get install -y libudev-dev

    - name: Generate rustdoc documentation
      run: |
        cargo xtask doc pages/doc/
        mv site/* pages/

    - name: Generate book
      run: |
        cd book && mdbook build

    - name: Deploy to Github Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: pages
